# Generated by Django 2.2.8 on 2020-03-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description! Lorem ipsum saduerwlnlewwjrlj'),
            preserve_default=False,
        ),
    ]
